name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            asset_name: click-me
          - os: macos-latest
            asset_name: click-me
          - os: windows-latest
            asset_name: click-me.exe

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Cache cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}

    - name: Build
      run: cargo b

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: get-paths-${{ runner.os }}
        path: target/debug/${{ matrix.asset_name }}
